general.import = ["./rose-pine.toml", "./local.toml"]

[window]
title = "Terminal"


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[cursor]
style.blinking = "On"

[terminal]
shell = "/bin/zsh"
osc52 = "CopyPaste"
